PROJECT_NAME = 'CSV to PostgresDB'
EXPORT_METADATA_CATEGOROY = 'EXPORT_METADATA_CATEGOROY'
EXPORT_METADATA_FIELD_1_NAME = 'EXPORT_METADATA_FIELD_1_NAME'
EXPORT_METADATA_FIELD_1_VALUES = ['VALUE_1', 'VALUE_2', 'VALUE_3']
EXPORT_METADATA_FIELD_2_NAME = 'EXPORT_METADATA_FIELD_2_NAME'
EXPORT_METADATA_FIELD_2_VALUES = ['VALUE_1', 'VALUE_2', 'VALUE_3']
EXPORT_METADATA_FIELD_3_NAME = 'EXPORT_METADATA_FIELD_3_NAME'
EXPORT_METADATA_FIELD_3_VALUES = ['VALUE_1', 'VALUE_2', 'VALUE_3']
